import type { GetStaticProps, InferGetStaticPropsType } from 'next';
import { type NextPage } from 'next';
import Head from 'next/head';
import { useRef, useState } from 'react';
import AddToCart from '../components/AddToCart';
import ProductList from '../components/ProductList';
import { getProducts } from '../lib/products';
import type { Product } from '../types/Product';

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  products,
}) => {
  const scrollToRef = useRef<HTMLElement>(null);

  const [chosenProduct, setChosenProduct] = useState<Product>();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex min-h-full w-full flex-col bg-orange-100 font-roboto-slab'>
        <header className='relative flex h-screen w-screen items-center justify-center bg-[url("../assets/hero.jpg")] bg-cover bg-center'>
          <div className='relative z-10 text-stone-50'>
            <h1 className='flex flex-col items-center'>
              <span className='self-start text-2xl text-amber-500 sm:text-3xl'>
                Welcome to
              </span>
              <span className='text-5xl drop-shadow-xl sm:text-7xl'>
                Smooth Pizza
              </span>
            </h1>
            <div className='mt-10 flex w-full justify-center'>
              <button
                className='px-5 py-1.5 text-xl ring-1 ring-stone-50 transition-all hover:text-amber-500 hover:ring-amber-500 focus-visible:text-amber-500 focus-visible:outline-none  focus-visible:ring-amber-500'
                onClick={() =>
                  scrollToRef.current?.scrollIntoView({
                    behavior: 'smooth',
                  })
                }
              >
                <span>Order now</span>
              </button>
            </div>
          </div>
          <div className='absolute top-[var(--navbar-height)] left-0 h-[calc(100vh_-_var(--navbar-height))] w-full bg-gradient-to-t from-stone-900/80 via-stone-900/50' />
        </header>
        <section
          ref={scrollToRef}
          className='flex w-full flex-col items-center py-[calc(var(--navbar-height)_+_1rem)] text-stone-900'
        >
          <div>
            <h2 className='text-4xl sm:text-5xl'>Our Menu</h2>
          </div>
          <ProductList
            products={products}
            setChosenProduct={setChosenProduct}
          />
        </section>
        <footer className='flex w-full flex-col items-center justify-center gap-4 bg-stone-900 p-4 text-stone-50'>
          <h2 className='text-4xl sm:text-5xl'>Contact</h2>
          <div>
            <div>
              <span>Address: </span>
              61260 Bruce Ramp, Waltermouth 03249-6796
            </div>
            <div>
              <span>Phone: </span>
              (575) 623-6790
            </div>
          </div>
          <a
            href='https://github.com/matibox/smooth-pizza'
            target='_blank'
            className='hover:text-amber-600'
            rel='noreferrer'
          >
            github
          </a>
        </footer>
      </div>
      {chosenProduct && (
        <AddToCart product={chosenProduct} setProduct={setChosenProduct} />
      )}
    </>
  );
};

export const getStaticProps: GetStaticProps<{
  products: Product[];
}> = async () => {
  const data = await getProducts();

  return {
    props: {
      products: data,
    },
    revalidate: 60,
  };
};

export default Home;
